title: EVA Development
description: >- # this means to ignore newlines until "baseurl:"
  EVA Development is a software developer specializing in mobile development,
  backend, and computer vision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evadevelopment.github.io" # the base hostname & protocol for your site, e.g. http://example.com

copyright: '© LLP "EVA Development" (BIN 220740019942), 2022'
email_base: "kzevjeny+evadevelopment@gmail.com"
email_contact_us: "kzevjeny+evadevelopment@gmail.com?subject=EVA%20Development"
telegram: "https://t.me/eva_development"

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
